name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/upload-artifact@v2
      with:
        name: SecretAdmin ${{ env.RUNNER_OS }}
        path: | 
          SecretAdmin/bin/Debug/net5.0/SecretAdmin
          SecretAdmin/bin/Debug/net5.0/SecretAdmin.exe
        if-no-files-found: error
